# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),debug)
  OBJDIR     = obj/linux/debug
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/sail
  DEFINES   += -DDEBUG
  INCLUDES  += -Ilib/stb_image
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += -lGL -lglfw -lGLEW
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/linux/release
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/sail
  DEFINES   += -DNDEBUG
  INCLUDES  += 
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -Wall
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += -lGL -lglfw -lGLEW
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
		$(OBJDIR)/main.o \
		$(OBJDIR)/Helper.o \
		$(OBJDIR)/Bitmap.o \
		$(OBJDIR)/Texture.o \
		$(OBJDIR)/Program.o \
		$(OBJDIR)/Shader.o \
		$(OBJDIR)/Camera.o \
		$(OBJDIR)/Cubemap.o \
		$(OBJDIR)/ObjLoader.o \
		$(OBJDIR)/Ocean.o \
		$(OBJDIR)/Complex.o \
		$(OBJDIR)/fft.o \
		$(OBJDIR)/vector.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
		@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
		@echo Linking Sail
		$(SILENT) $(LINKCMD)
		$(POSTBUILDCMDS)

$(TARGETDIR):
		@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
		$(SILENT) mkdir -p $(TARGETDIR)
else
		$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
		@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
		$(SILENT) mkdir -p $(OBJDIR)
else
		$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
		@echo Cleaning Sail
ifeq (posix,$(SHELLTYPE))
		$(SILENT) rm -f  $(TARGET)
		$(SILENT) rm -rf $(OBJDIR)
else
		$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
		$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
		$(PREBUILDCMDS)

prelink:
		$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
		@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
		-$(SILENT) cp $< $(OBJDIR)
else
		$(SILENT) xcopy /D /Y /Q "$(subst /,\,$<)" "$(subst /,\,$(OBJDIR))" 1>nul
endif
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
endif

$(OBJDIR)/Program.o: src/ogl/Program.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Helper.o: src/Helper.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/main.o: src/main.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Shader.o: src/ogl/Shader.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Bitmap.o: src/ogl/Bitmap.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Texture.o: src/ogl/Texture.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Camera.o: src/ogl/Camera.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Cubemap.o: src/ogl/Cubemap.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ObjLoader.o: src/ogl/ObjLoader.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Ocean.o: src/entities/Ocean.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Complex.o: src/entities/Complex.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/fft.o: src/entities/fft.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/vector.o: src/entities/vector.cpp
		@echo $(notdir $<)
		$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"


-include $(OBJECTS:%.o=%.d)

